print(len(
    'Te explicamos cuales son las mejores marcas de laptops que existen, en donde comprarlas y porque son las más reconocidas del mercado.'))
data = {
        # 'metadescription': metadescription,
        # # 'robots_directivas': robots_directivas,
        # 'lenguaje': lenguaje,
        # 'canonical': canonical,
        # # 'etiquetas': etiquetas,
        'url': 0,
        'url_len': 0,
        'wourd count': 0,
        'puerto': 0,
        'text_length': 0,
        'links_internos': 0,
        'links_externos': 0,
        'size_pagina': 0,
        'lenImagenes': 0,
        'text_radio': 0,
        'len_h_uno': 0,
        'len_h_dos': 0,
        'len_h_tres': 0,
        'len_h_cuatro': 0,
        'len_h_cinco': 0,
        'len_h_seis': 0,
        'len_metadescription': 0,
        'len_metatitulo': 0,
        'Categoria': '1'}